version: "3.5"

services:
  client:
    restart: always
    container_name: client
    build:
      context: client
      target: development
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    container_name: server
    restart: always
    depends_on:
      - db
    build:
      context: server
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: "yarn run dev"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
