version: "3.5"

services:
  client:
    container_name: client
    build:
      context: client
      target: production
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: server
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    networks:
      - app-network
      
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "nexus-dev.duckdns.org -> http://client:3000, api.nexus-dev.duckdns.org -> http://server:8000"
      STAGE: "production" # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
      - app-network

volumes:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
networks:
  app-network:
